#!/bin/bash

# Usage: invoke_remote_lambda [CloudFormation output key] [Payload for Lambda function]
# Example: invoke_remote_lambda MyFunctionArn '{"some": "json"}'

set -e

function samConfigVal {
    grep $1 ../samconfig.toml | awk -F\= '{gsub(/"/, "", $2); gsub(/ /, "", $2); print $2}'
}

stack_name=$(samConfigVal "stack_name")
region=$(samConfigVal "region")

function getStackOutput {
    aws cloudformation describe-stacks --region=$region --stack-name $stack_name --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

arn=$(getStackOutput $1)
payload=$2

aws lambda invoke \
--region=$region \
--cli-binary-format raw-in-base64-out \
--function-name "$arn" \
--payload "$payload" \
/dev/stdout